import type { SkillManifest } from "@copilotchat/shared";
export const builtInSkills: SkillManifest[] = [
  { id: "code-review", name: "Code review", description: "Review diffs and workspace changes for correctness, security, and regression risk.", version: "1.0.0", instructions: "Focus on bugs, security issues, logic errors, data loss, and broken user-visible behavior. Avoid style-only feedback.", prompts: [], workflow: ["Inspect repository status", "Read changed files", "Run targeted tests"], artifactTemplates: [], mcpDependencies: [], toolDependencies: ["workspace.read", "workspace.command"], activationRules: ["User asks for review"], permissions: ["filesystem:read", "shell"] },
  { id: "planning", name: "Implementation planning", description: "Create structured implementation plans for larger changes.", version: "1.0.0", instructions: "Analyze current state, identify risks and dependencies, ask clarifying questions if needed, then produce phased plans with validation steps.", prompts: [], workflow: ["Explore", "Identify decisions", "Write phased plan"], artifactTemplates: [], mcpDependencies: [], toolDependencies: ["artifact.create"], activationRules: ["User asks for a plan"], permissions: ["artifacts"] },
  { id: "debugging", name: "Debugging", description: "Investigate failures, reproduce issues, isolate root causes, and propose fixes.", version: "1.0.0", instructions: "Reproduce before changing code when practical. Prefer narrow fixes that address root cause.", prompts: [], workflow: ["Collect error", "Find code", "Reproduce", "Patch", "Validate"], artifactTemplates: [], mcpDependencies: [], toolDependencies: ["workspace.command", "workspace.read"], activationRules: ["User shares an error"], permissions: ["filesystem:read", "filesystem:write", "shell"] },
  { id: "research", name: "Research", description: "Research current technical information and summarize findings.", version: "1.0.0", instructions: "Use web or repository research tools when current information is needed. Separate verified facts from uncertainty.", prompts: [], workflow: ["Search sources", "Read docs", "Cross-check", "Summarize"], artifactTemplates: [], mcpDependencies: [], toolDependencies: ["web.search", "web.fetch"], activationRules: ["User asks for research"], permissions: ["network"] },
  { id: "artifact-generation", name: "Artifact generation", description: "Create reusable Markdown, code, HTML, JSON, and Mermaid artifacts.", version: "1.0.0", instructions: "When output would be reused, create an artifact with a clear title, kind, language, and content.", prompts: [], workflow: ["Choose artifact type", "Draft", "Preview", "Version updates"], artifactTemplates: [], mcpDependencies: [], toolDependencies: ["artifact.create"], activationRules: ["User asks for a document"], permissions: ["artifacts"] },
  { id: "import-assistant", name: "Import assistant", description: "Guide Claude, ChatGPT, and Gemini imports with preview, project-mapping checks, and confirmation before applying.", version: "1.0.0", instructions: "Help the user import assistant exports carefully. First call preview_import_draft for uploaded drafts and summarize conversation, project, reference, warning, and likely project-mapping counts. For Claude and ChatGPT project imports, explicitly ask the user for screenshots or copied text of project conversation lists when project membership could be incomplete or ambiguous; if this chat cannot read an image, ask them to paste the visible project names and conversation titles from the screenshot. Use set_import_project_assignments to correct project membership from those titles before applying. Do not call apply_import_draft until the user clearly confirms they are ready to import. After applying, summarize imported conversations, projects, warnings, and any conversations that may still need manual review.", prompts: [{ id: "guided-import", title: "Guide an assistant export import", body: "Preview this import draft, ask for project conversation screenshots or pasted title lists if they would improve mapping, then apply only after I confirm." }], workflow: ["Preview the uploaded import draft", "Explain detected source, counts, projects, and warnings", "Ask for project conversation screenshots or pasted title lists when membership is ambiguous", "Set project assignment overrides from the evidence", "Ask for explicit confirmation", "Apply the import and summarize results"], artifactTemplates: [], mcpDependencies: [], toolDependencies: ["preview_import_draft", "set_import_project_assignments", "apply_import_draft"], activationRules: ["User wants to import Claude conversations", "User wants to import ChatGPT conversations", "User uploads an assistant export", "User mentions an import draft"], permissions: [] },
];
