import { randomUUID } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import Database from "better-sqlite3";
import type { AppState, Artifact, ArtifactSummary, Chat, ChatMessage, ConversationScope, ConversationSearchResult, ConversationSummary, ConversationTranscript, CreateArtifactRequest, CreateChatRequest, CreateProjectReferenceRequest, CreateProjectRequest, McpServer, MessageAttachment, Owner, Project, ProjectChatReference, ProjectChatSearchResult, ProjectReference, ProviderStatus, RegisterWorkspaceRequest, Skill, SkillManifest, ToolRun, UpdateArtifactRequest, UpdateChatRequest, UpdateMcpServerRequest, UpdateProjectReferenceRequest, UpdateProjectRequest, UpdateSkillRequest, UpdateWorkspaceRequest, Workspace } from "@copilotchat/shared";
import { builtInSkills } from "./builtins.js";

type Row = Record<string, unknown>;
type GitHubAuthInput = { accessToken: string; login: string; displayName: string | null; avatarUrl: string | null };
const maxMessageMetadataLength = 25_000_000;

export class AppDatabase {
  private readonly db: Database.Database;
  constructor(dataDir: string) { fs.mkdirSync(dataDir, { recursive: true }); this.db = new Database(path.join(dataDir, "copilotchat.sqlite")); this.db.pragma("journal_mode = WAL"); this.db.pragma("foreign_keys = ON"); this.migrate(); this.seed(); }

  getOwner(): Owner { const row = this.db.prepare("SELECT * FROM owners ORDER BY created_at LIMIT 1").get() as Row | undefined; if (!row) throw new Error("Local owner was not initialized."); return mapOwner(row); }
  getOwnerById(ownerId: string): Owner { const row = this.db.prepare("SELECT * FROM owners WHERE id = ?").get(ownerId) as Row | undefined; if (!row) throw new Error("Owner not found."); return mapOwner(row); }
  getOrCreateGitHubOwner(input: { login: string; displayName: string | null; avatarUrl: string | null }): Owner {
    const id = `github:${input.login.toLowerCase()}`;
    const existing = this.db.prepare("SELECT * FROM owners WHERE id = ?").get(id) as Row | undefined;
    const now = iso();
    if (existing) {
      this.db.prepare("UPDATE owners SET login = ?, display_name = ?, avatar_url = ?, auth_provider = 'github' WHERE id = ?").run(input.login, input.displayName, input.avatarUrl, id);
      return this.getOwnerById(id);
    }
    this.db.prepare("INSERT INTO owners (id, login, display_name, avatar_url, auth_provider, created_at) VALUES (?, ?, ?, ?, 'github', ?)").run(id, input.login, input.displayName, input.avatarUrl, now);
    for (const skill of builtInSkills) this.upsertSkill(id, skill, true, null);
    return this.getOwnerById(id);
  }
  hasGitHubAuth(ownerId = this.getOwner().id): boolean { return Boolean(this.db.prepare("SELECT 1 FROM auth_tokens WHERE provider = 'github' AND owner_id = ?").get(ownerId) as Row | undefined); }
  getGitHubToken(ownerId = this.getOwner().id): string | null { const row = this.db.prepare("SELECT access_token FROM auth_tokens WHERE provider = 'github' AND owner_id = ?").get(ownerId) as Row | undefined; return nullableString(row?.access_token); }
  setGitHubAuth(input: GitHubAuthInput): Owner;
  setGitHubAuth(ownerId: string, input: GitHubAuthInput): Owner;
  setGitHubAuth(ownerOrInput: string | GitHubAuthInput, explicitInput?: GitHubAuthInput): Owner { const ownerId = typeof ownerOrInput === "string" ? ownerOrInput : this.getOwner().id; const input = typeof ownerOrInput === "string" ? explicitInput : ownerOrInput; if (!input) throw new Error("GitHub auth details are required."); const now = iso(); this.getOwnerById(ownerId); this.db.prepare(`INSERT INTO auth_tokens (provider, owner_id, access_token, created_at, updated_at) VALUES ('github', ?, ?, ?, ?) ON CONFLICT(provider, owner_id) DO UPDATE SET access_token = excluded.access_token, updated_at = excluded.updated_at`).run(ownerId, input.accessToken, now, now); this.db.prepare("UPDATE owners SET login = ?, display_name = ?, avatar_url = ?, auth_provider = 'github' WHERE id = ?").run(input.login, input.displayName, input.avatarUrl, ownerId); return this.getOwnerById(ownerId); }
  getState(provider: ProviderStatus, activeChatIds: string[] = [], ownerId = this.getOwner().id, authMode: AppState["authMode"] = "local"): AppState { const owner = this.getOwnerById(ownerId); return { owner, authMode, projects: this.listProjects(owner.id), projectReferences: this.listProjectReferences(owner.id), projectChatReferences: this.listProjectChatReferences(owner.id), chats: this.listChats(owner.id), archivedChats: this.listArchivedChats(owner.id), artifacts: this.listArtifactSummaries(owner.id), skills: this.listSkills(owner.id), mcpServers: this.listMcpServers(owner.id), workspaces: this.listWorkspaces(owner.id), provider, activeChatIds }; }

  listProjects(ownerId: string): Project[] { return (this.db.prepare("SELECT * FROM projects WHERE owner_id = ? ORDER BY favorite DESC, updated_at DESC").all(ownerId) as Row[]).map(mapProject); }
  createProject(ownerId: string, input: CreateProjectRequest): Project { const now = iso(); const id = randomUUID(); this.db.prepare("INSERT INTO projects (id, owner_id, name, description, instructions, memory, default_model, favorite, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, 0, ?, ?)").run(id, ownerId, input.name, input.description ?? null, input.instructions ?? null, input.memory ?? null, input.defaultModel ?? null, now, now); return this.getProject(ownerId, id); }
  getProject(ownerId: string, projectId: string): Project { const row = this.db.prepare("SELECT * FROM projects WHERE owner_id = ? AND id = ?").get(ownerId, projectId) as Row | undefined; if (!row) throw new Error("Project not found."); return mapProject(row); }
  updateProject(ownerId: string, projectId: string, input: UpdateProjectRequest): Project { const cur = this.getProject(ownerId, projectId); const now = iso(); const nextInstructions = input.instructions === undefined ? cur.instructions : input.instructions; const nextMemory = input.memory === undefined ? cur.memory : input.memory; const nextDefaultModel = input.defaultModel === undefined ? cur.defaultModel : input.defaultModel; const contextChanged = nextInstructions !== cur.instructions || nextMemory !== cur.memory || nextDefaultModel !== cur.defaultModel; this.db.prepare("UPDATE projects SET name = ?, description = ?, instructions = ?, memory = ?, default_model = ?, favorite = ?, updated_at = ? WHERE owner_id = ? AND id = ?").run(input.name ?? cur.name, input.description === undefined ? cur.description : input.description, nextInstructions, nextMemory, nextDefaultModel, input.favorite === undefined ? (cur.favorite ? 1 : 0) : input.favorite ? 1 : 0, now, ownerId, projectId); if (contextChanged) this.clearProjectProviderSessions(ownerId, projectId, now); return this.getProject(ownerId, projectId); }
  deleteProject(ownerId: string, projectId: string): void { this.db.prepare("DELETE FROM projects WHERE owner_id = ? AND id = ?").run(ownerId, projectId); }
  listProjectReferences(ownerId: string, projectId?: string): ProjectReference[] { const rows = projectId ? this.db.prepare("SELECT * FROM project_references WHERE owner_id = ? AND project_id = ? ORDER BY updated_at DESC").all(ownerId, projectId) : this.db.prepare("SELECT * FROM project_references WHERE owner_id = ? ORDER BY updated_at DESC").all(ownerId); return (rows as Row[]).map(mapProjectReference); }
  createProjectReference(ownerId: string, input: CreateProjectReferenceRequest): ProjectReference { this.getProject(ownerId, input.projectId); const now = iso(); const id = randomUUID(); this.db.prepare("INSERT INTO project_references (id, owner_id, project_id, title, content, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)").run(id, ownerId, input.projectId, input.title, input.content, now, now); this.clearProjectProviderSessions(ownerId, input.projectId, now); return mapProjectReference(this.db.prepare("SELECT * FROM project_references WHERE id = ?").get(id) as Row); }
  updateProjectReference(ownerId: string, id: string, input: UpdateProjectReferenceRequest): ProjectReference { const current = this.db.prepare("SELECT * FROM project_references WHERE owner_id = ? AND id = ?").get(ownerId, id) as Row | undefined; if (!current) throw new Error("Project reference not found."); const now = iso(); this.db.prepare("UPDATE project_references SET title = ?, content = ?, updated_at = ? WHERE owner_id = ? AND id = ?").run(input.title ?? String(current.title), input.content ?? String(current.content), now, ownerId, id); this.clearProjectProviderSessions(ownerId, String(current.project_id), now); return mapProjectReference(this.db.prepare("SELECT * FROM project_references WHERE id = ?").get(id) as Row); }
  deleteProjectReference(ownerId: string, id: string): void { const row = this.db.prepare("SELECT project_id FROM project_references WHERE owner_id = ? AND id = ?").get(ownerId, id) as Row | undefined; this.db.prepare("DELETE FROM project_references WHERE owner_id = ? AND id = ?").run(ownerId, id); if (row) this.clearProjectProviderSessions(ownerId, String(row.project_id), iso()); }
  listProjectChatReferences(ownerId: string, projectId?: string): ProjectChatReference[] { const rows = projectId ? this.db.prepare("SELECT * FROM project_chat_references WHERE owner_id = ? AND project_id = ? ORDER BY created_at DESC").all(ownerId, projectId) : this.db.prepare("SELECT * FROM project_chat_references WHERE owner_id = ? ORDER BY created_at DESC").all(ownerId); return (rows as Row[]).map(mapProjectChatReference); }
  createProjectChatReference(ownerId: string, input: { projectId: string; messageId: string }): ProjectChatReference { this.getProject(ownerId, input.projectId); const existing = this.db.prepare("SELECT * FROM project_chat_references WHERE owner_id = ? AND project_id = ? AND source_message_id = ?").get(ownerId, input.projectId, input.messageId) as Row | undefined; if (existing) return mapProjectChatReference(existing); const row = this.db.prepare("SELECT messages.*, chats.title AS chat_title, chats.project_id AS project_id, chats.owner_id AS owner_id FROM messages JOIN chats ON chats.id = messages.chat_id WHERE messages.id = ? AND chats.owner_id = ?").get(input.messageId, ownerId) as Row | undefined; if (!row) throw new Error("Message not found."); if (String(row.project_id) !== input.projectId) throw new Error("Message is not in this project."); const now = iso(); const id = randomUUID(); const excerpt = excerptText(String(row.content)); this.db.prepare("INSERT INTO project_chat_references (id, owner_id, project_id, source_chat_id, source_message_id, title, excerpt, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)").run(id, ownerId, input.projectId, String(row.chat_id), input.messageId, String(row.chat_title), excerpt, now); this.clearProjectProviderSessions(ownerId, input.projectId, now); return mapProjectChatReference(this.db.prepare("SELECT * FROM project_chat_references WHERE id = ?").get(id) as Row); }
  deleteProjectChatReference(ownerId: string, id: string): void { const row = this.db.prepare("SELECT project_id FROM project_chat_references WHERE owner_id = ? AND id = ?").get(ownerId, id) as Row | undefined; this.db.prepare("DELETE FROM project_chat_references WHERE owner_id = ? AND id = ?").run(ownerId, id); if (row) this.clearProjectProviderSessions(ownerId, String(row.project_id), iso()); }
  searchProjectMessages(ownerId: string, projectId: string, query: string): ProjectChatSearchResult[] { this.getProject(ownerId, projectId); const like = `%${query.trim()}%`; if (!query.trim()) return []; return (this.db.prepare("SELECT chats.id AS chat_id, messages.id AS message_id, chats.title AS title, messages.role AS role, messages.content AS content, messages.created_at AS created_at FROM messages JOIN chats ON chats.id = messages.chat_id WHERE chats.owner_id = ? AND chats.project_id = ? AND messages.content LIKE ? ORDER BY messages.created_at DESC LIMIT 20").all(ownerId, projectId, like) as Row[]).map((row) => ({ chatId: String(row.chat_id), messageId: String(row.message_id), title: String(row.title), role: normalizeRole(row.role), excerpt: excerptText(String(row.content)), createdAt: String(row.created_at) })); }
  searchConversations(ownerId: string, query: string, options: { scope: ConversationScope; currentProjectId: string | null; excludeChatId?: string | null; limit?: number }): ConversationSearchResult[] { const trimmed = query.trim(); if (!trimmed) return []; const limit = clampLimit(options.limit, 20, 50); const scope = conversationScopeClause(options.scope, options.currentProjectId, options.excludeChatId ?? null); return (this.db.prepare(`SELECT chats.id AS chat_id, chats.title AS chat_title, chats.project_id AS project_id, projects.name AS project_name, messages.id AS message_id, messages.role AS role, messages.content AS content, messages.created_at AS created_at FROM messages JOIN chats ON chats.id = messages.chat_id LEFT JOIN projects ON projects.id = chats.project_id WHERE chats.owner_id = ?${scope.clause} AND messages.content LIKE ? ORDER BY messages.created_at DESC LIMIT ?`).all(ownerId, ...scope.params, `%${trimmed}%`, limit) as Row[]).map((row) => ({ chatId: String(row.chat_id), chatTitle: String(row.chat_title), projectId: nullableString(row.project_id), projectName: nullableString(row.project_name), messageId: String(row.message_id), role: normalizeRole(row.role), excerpt: excerptText(String(row.content)), createdAt: String(row.created_at) })); }
  listRecentConversations(ownerId: string, options: { scope: ConversationScope; currentProjectId: string | null; excludeChatId?: string | null; includeArchived?: boolean; limit?: number }): ConversationSummary[] { const limit = clampLimit(options.limit, 20, 50); const scope = conversationScopeClause(options.scope, options.currentProjectId, options.excludeChatId ?? null); const archivedClause = options.includeArchived ? "" : " AND chats.archived = 0"; return (this.db.prepare(`SELECT chats.id AS chat_id, chats.title AS title, chats.project_id AS project_id, projects.name AS project_name, chats.archived AS archived, chats.favorite AS favorite, chats.created_at AS created_at, chats.updated_at AS updated_at, (SELECT COUNT(*) FROM messages WHERE messages.chat_id = chats.id) AS message_count FROM chats LEFT JOIN projects ON projects.id = chats.project_id WHERE chats.owner_id = ?${scope.clause}${archivedClause} ORDER BY chats.updated_at DESC LIMIT ?`).all(ownerId, ...scope.params, limit) as Row[]).map((row) => ({ chatId: String(row.chat_id), title: String(row.title), projectId: nullableString(row.project_id), projectName: nullableString(row.project_name), archived: Boolean(row.archived), favorite: Boolean(row.favorite), messageCount: Number(row.message_count ?? 0), createdAt: String(row.created_at), updatedAt: String(row.updated_at) })); }
  getConversationTranscript(ownerId: string, chatId: string, options?: { limit?: number; maxContentLength?: number }): ConversationTranscript { const chat = this.getChat(ownerId, chatId); const projectRow = chat.projectId ? this.db.prepare("SELECT name FROM projects WHERE owner_id = ? AND id = ?").get(ownerId, chat.projectId) as Row | undefined : undefined; const all = this.listMessages(chatId); const limit = clampLimit(options?.limit, 40, 200); const maxContentLength = clampLimit(options?.maxContentLength, 4000, 20000); const selected = all.slice(Math.max(0, all.length - limit)); return { chatId: chat.id, title: chat.title, projectId: chat.projectId, projectName: projectRow ? String(projectRow.name) : null, messageCount: all.length, truncated: selected.length < all.length, messages: selected.map((message) => ({ id: message.id, role: message.role, content: clampContent(message.content, maxContentLength), createdAt: message.createdAt })) }; }

  listChats(ownerId: string): Chat[] { return (this.db.prepare("SELECT * FROM chats WHERE owner_id = ? AND archived = 0 ORDER BY favorite DESC, updated_at DESC").all(ownerId) as Row[]).map(mapChat); }
  listArchivedChats(ownerId: string): Chat[] { return (this.db.prepare("SELECT * FROM chats WHERE owner_id = ? AND archived = 1 ORDER BY updated_at DESC").all(ownerId) as Row[]).map(mapChat); }
  createChat(ownerId: string, input: CreateChatRequest): Chat { const now = iso(); const id = randomUUID(); this.db.prepare("INSERT INTO chats (id, owner_id, project_id, workspace_id, model, reasoning_effort, context_tier, title, title_manually_set, archived, favorite, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 0, 0, 0, ?, ?)").run(id, ownerId, input.projectId ?? null, input.workspaceId ?? null, input.model ?? null, input.reasoningEffort ?? null, input.contextTier ?? null, input.title, now, now); return this.getChat(ownerId, id); }
  getChat(ownerId: string, chatId: string): Chat { const row = this.db.prepare("SELECT * FROM chats WHERE owner_id = ? AND id = ?").get(ownerId, chatId) as Row | undefined; if (!row) throw new Error("Chat not found."); return mapChat(row); }
  updateChatTitle(ownerId: string, chatId: string, title: string, source: "auto" | "manual" = "manual"): Chat { const cur = this.getChat(ownerId, chatId); const now = iso(); this.db.prepare("UPDATE chats SET title = ?, title_manually_set = ?, updated_at = ? WHERE owner_id = ? AND id = ?").run(title, source === "manual" || cur.titleManuallySet ? 1 : 0, now, ownerId, chatId); return this.getChat(ownerId, chatId); }
  updateChat(ownerId: string, chatId: string, input: UpdateChatRequest): Chat { const cur = this.getChat(ownerId, chatId); const now = iso(); const nextProjectId = input.projectId === undefined ? cur.projectId : input.projectId; const nextWorkspaceId = input.workspaceId === undefined ? cur.workspaceId : input.workspaceId; const nextModel = input.model === undefined ? cur.model : input.model; const nextReasoningEffort = input.reasoningEffort === undefined ? cur.reasoningEffort : input.reasoningEffort; const nextContextTier = input.contextTier === undefined ? cur.contextTier : input.contextTier; const providerContextChanged = nextProjectId !== cur.projectId || nextWorkspaceId !== cur.workspaceId || nextModel !== cur.model || nextReasoningEffort !== cur.reasoningEffort || nextContextTier !== cur.contextTier; this.db.prepare("UPDATE chats SET title = ?, title_manually_set = ?, archived = ?, favorite = ?, project_id = ?, workspace_id = ?, model = ?, reasoning_effort = ?, context_tier = ?, provider_session_id = ?, provider_session_workspace_path = ?, updated_at = ? WHERE owner_id = ? AND id = ?").run(input.title ?? cur.title, input.title === undefined ? (cur.titleManuallySet ? 1 : 0) : 1, input.archived === undefined ? (cur.archived ? 1 : 0) : input.archived ? 1 : 0, input.favorite === undefined ? (cur.favorite ? 1 : 0) : input.favorite ? 1 : 0, nextProjectId, nextWorkspaceId, nextModel, nextReasoningEffort, nextContextTier, providerContextChanged ? null : cur.providerSessionId, providerContextChanged ? null : cur.providerSessionWorkspacePath, now, ownerId, chatId); return this.getChat(ownerId, chatId); }
  setChatProviderSession(ownerId: string, chatId: string, input: { providerSessionId: string; providerSessionWorkspacePath?: string | null }): Chat { const now = iso(); this.db.prepare("UPDATE chats SET provider_session_id = ?, provider_session_workspace_path = ?, updated_at = ? WHERE owner_id = ? AND id = ?").run(input.providerSessionId, input.providerSessionWorkspacePath ?? null, now, ownerId, chatId); return this.getChat(ownerId, chatId); }
  deleteChat(ownerId: string, chatId: string): void { this.db.prepare("DELETE FROM chats WHERE owner_id = ? AND id = ?").run(ownerId, chatId); }
  deleteEmptyChats(ownerId: string, exceptChatId?: string | null): string[] { const rows = this.db.prepare("SELECT chats.id FROM chats WHERE chats.owner_id = ? AND chats.archived = 0 AND (? IS NULL OR chats.id != ?) AND NOT EXISTS (SELECT 1 FROM messages WHERE messages.chat_id = chats.id)").all(ownerId, exceptChatId ?? null, exceptChatId ?? null) as Row[]; const ids = rows.map((row) => String(row.id)); if (ids.length > 0) this.db.prepare(`DELETE FROM chats WHERE owner_id = ? AND id IN (${ids.map(() => "?").join(",")})`).run(ownerId, ...ids); return ids; }
  listMessages(chatId: string, options: { includeAttachmentData?: boolean } = {}): ChatMessage[] { const messages = (this.db.prepare("SELECT id, chat_id, role, content, provider, CASE WHEN length(metadata) > ? THEN '{}' ELSE metadata END AS metadata, created_at FROM messages WHERE chat_id = ? ORDER BY created_at ASC").all(maxMessageMetadataLength, chatId) as Row[]).map(mapMessage); return messages.map((message) => { const attachments = this.listMessageAttachments(message.id, Boolean(options.includeAttachmentData)); return attachments.length ? { ...message, metadata: { ...message.metadata, attachments } } : message; }); }
  addMessage(input: { chatId: string; role: ChatMessage["role"]; content: string; provider?: string | null; metadata?: Record<string, unknown>; createdAt?: string | null }): ChatMessage { const now = input.createdAt ?? iso(); const id = randomUUID(); this.db.prepare("INSERT INTO messages (id, chat_id, role, content, provider, metadata, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)").run(id, input.chatId, input.role, input.content, input.provider ?? null, stringify(withoutRuntimeAttachments(input.metadata ?? {})), now); this.db.prepare("UPDATE chats SET updated_at = ? WHERE id = ?").run(now, input.chatId); return mapMessage(this.db.prepare("SELECT * FROM messages WHERE id = ?").get(id) as Row); }
  listMessageAttachments(messageId: string, includeData = true): MessageAttachment[] { const dataColumn = includeData ? "data" : "NULL AS data"; return (this.db.prepare(`SELECT id, name, mime_type, size, ${dataColumn} FROM message_attachments WHERE message_id = ? ORDER BY created_at, id`).all(messageId) as Row[]).map(mapMessageAttachment); }
  replaceMessageAttachments(ownerId: string, chatId: string, messageId: string, attachments: MessageAttachment[]): void {
    this.getChat(ownerId, chatId);
    const now = iso();
    const run = this.db.transaction(() => {
      this.db.prepare("DELETE FROM message_attachments WHERE message_id = ?").run(messageId);
      for (const attachment of attachments) this.db.prepare("INSERT INTO message_attachments (id, owner_id, chat_id, message_id, name, mime_type, size, data, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)").run(attachment.id, ownerId, chatId, messageId, attachment.name, attachment.mimeType, attachment.size, attachment.data, now);
    });
    run();
  }
  editUserMessageAndTruncate(ownerId: string, chatId: string, messageId: string, content: string): ChatMessage {
    this.getChat(ownerId, chatId);
    const messages = this.listMessages(chatId); const index = messages.findIndex((message) => message.id === messageId); if (index < 0) throw new Error("Message not found."); const message = messages[index]; if (!message || message.role !== "user") throw new Error("Only user messages can be edited."); const removedIds = messages.slice(index + 1).map((m) => m.id); const now = iso();
    const run = this.db.transaction(() => {
      if (removedIds.length > 0) this.db.prepare(`DELETE FROM messages WHERE id IN (${removedIds.map(() => "?").join(",")})`).run(...removedIds);
      this.db.prepare(`DELETE FROM artifacts WHERE chat_id = ? AND (message_id = ?${removedIds.length > 0 ? ` OR message_id IN (${removedIds.map(() => "?").join(",")})` : ""})`).run(chatId, messageId, ...removedIds);
      this.db.prepare("UPDATE messages SET content = ?, metadata = ? WHERE id = ?").run(content, stringify({ ...withoutRuntimeAttachments(message.metadata), editedAt: now }), messageId);
      this.db.prepare("UPDATE chats SET provider_session_id = NULL, provider_session_workspace_path = NULL, updated_at = ? WHERE id = ?").run(now, chatId);
    });
    run();
    return mapMessage(this.db.prepare("SELECT * FROM messages WHERE id = ?").get(messageId) as Row);
  }
  retryAssistantMessage(ownerId: string, chatId: string, messageId: string): ChatMessage {
    this.getChat(ownerId, chatId);
    const messages = this.listMessages(chatId); const index = messages.findIndex((message) => message.id === messageId); if (index < 0) throw new Error("Message not found."); const message = messages[index]; if (!message || message.role !== "assistant") throw new Error("Only assistant messages can be retried."); const userMessage = [...messages.slice(0, index)].reverse().find((m) => m.role === "user"); if (!userMessage) throw new Error("No user message found before assistant response."); const removedIds = messages.slice(index).map((m) => m.id); const now = iso();
    const run = this.db.transaction(() => {
      if (removedIds.length > 0) this.db.prepare(`DELETE FROM messages WHERE id IN (${removedIds.map(() => "?").join(",")})`).run(...removedIds);
      if (removedIds.length > 0) this.db.prepare(`DELETE FROM artifacts WHERE chat_id = ? AND message_id IN (${removedIds.map(() => "?").join(",")})`).run(chatId, ...removedIds);
      this.db.prepare("UPDATE chats SET provider_session_id = NULL, provider_session_workspace_path = NULL, updated_at = ? WHERE id = ?").run(now, chatId);
    });
    run();
    return userMessage;
  }

  listArtifacts(ownerId: string): Artifact[] { return (this.db.prepare("SELECT * FROM artifacts WHERE owner_id = ? ORDER BY updated_at DESC").all(ownerId) as Row[]).map(mapArtifact); }
  listArtifactSummaries(ownerId: string): ArtifactSummary[] { return (this.db.prepare("SELECT id, owner_id, project_id, chat_id, message_id, file_path, title, kind, language, version, created_at, updated_at, substr(content, 1, 1600) AS content_preview, length(content) AS content_length FROM artifacts WHERE owner_id = ? ORDER BY updated_at DESC").all(ownerId) as Row[]).map(mapArtifactSummary); }
  createArtifact(ownerId: string, input: CreateArtifactRequest): Artifact { const now = iso(); const id = randomUUID(); this.db.prepare("INSERT INTO artifacts (id, owner_id, project_id, chat_id, message_id, file_path, title, kind, language, content, version, created_at, updated_at) VALUES (?, ?, ?, ?, ?, NULL, ?, ?, ?, ?, 1, ?, ?)").run(id, ownerId, input.projectId ?? null, input.chatId ?? null, input.messageId ?? null, input.title, input.kind, input.language ?? null, input.content, now, now); return this.getArtifact(ownerId, id); }
  upsertArtifactFile(ownerId: string, input: CreateArtifactRequest & { filePath: string }): Artifact { const existing = this.db.prepare("SELECT * FROM artifacts WHERE owner_id = ? AND file_path = ?").get(ownerId, input.filePath) as Row | undefined; if (!existing) { const now = iso(); const id = randomUUID(); this.db.prepare("INSERT INTO artifacts (id, owner_id, project_id, chat_id, message_id, file_path, title, kind, language, content, version, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?, ?)").run(id, ownerId, input.projectId ?? null, input.chatId ?? null, input.messageId ?? null, input.filePath, input.title, input.kind, input.language ?? null, input.content, now, now); return this.getArtifact(ownerId, id); } const artifact = mapArtifact(existing); return this.updateArtifact(ownerId, artifact.id, { title: input.title, kind: input.kind, language: input.language ?? null, content: input.content }); }
  getArtifact(ownerId: string, id: string): Artifact { const row = this.db.prepare("SELECT * FROM artifacts WHERE owner_id = ? AND id = ?").get(ownerId, id) as Row | undefined; if (!row) throw new Error("Artifact not found."); return mapArtifact(row); }
  updateArtifact(ownerId: string, id: string, input: UpdateArtifactRequest): Artifact { const cur = this.getArtifact(ownerId, id); const changed = input.content !== undefined && input.content !== cur.content; const now = iso(); this.db.prepare("UPDATE artifacts SET title = ?, kind = ?, language = ?, content = ?, version = ?, updated_at = ? WHERE owner_id = ? AND id = ?").run(input.title ?? cur.title, input.kind ?? cur.kind, input.language === undefined ? cur.language : input.language, input.content ?? cur.content, changed ? cur.version + 1 : cur.version, now, ownerId, id); return this.getArtifact(ownerId, id); }
  deleteArtifact(ownerId: string, id: string): void { this.db.prepare("DELETE FROM artifacts WHERE owner_id = ? AND id = ?").run(ownerId, id); }

  listSkills(ownerId: string): Skill[] { return (this.db.prepare("SELECT * FROM skills WHERE owner_id = ? ORDER BY built_in DESC, json_extract(manifest, '$.name')").all(ownerId) as Row[]).map(mapSkill); }
  enabledSkillManifests(ownerId: string, skillIds?: string[], projectId?: string | null, content = ""): SkillManifest[] {
    const explicitIds = new Set(skillIds ?? []);
    return this.listSkills(ownerId)
      .filter((skill) => skill.enabled && (skill.projectId === null || skill.projectId === projectId) && shouldActivateSkill(skill, explicitIds, content))
      .map((skill) => skill.manifest);
  }
  upsertSkill(ownerId: string, manifest: SkillManifest, builtIn: boolean, projectId: string | null): Skill { const now = iso(); const id = skillRowId(ownerId, manifest.id); this.db.prepare(`INSERT INTO skills (id, owner_id, project_id, enabled, built_in, manifest, created_at, updated_at) VALUES (?, ?, ?, 1, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET manifest = excluded.manifest, built_in = excluded.built_in, updated_at = excluded.updated_at`).run(id, ownerId, projectId, builtIn ? 1 : 0, stringify(manifest), now, now); return this.getSkill(ownerId, id); }
  getSkill(ownerId: string, id: string): Skill { const row = this.db.prepare("SELECT * FROM skills WHERE owner_id = ? AND id = ?").get(ownerId, id) as Row | undefined; if (!row) throw new Error("Skill not found."); return mapSkill(row); }
  updateSkill(ownerId: string, id: string, input: UpdateSkillRequest): Skill { const cur = this.getSkill(ownerId, id); const now = iso(); this.db.prepare("UPDATE skills SET enabled = ?, manifest = ?, updated_at = ? WHERE owner_id = ? AND id = ?").run(input.enabled === undefined ? (cur.enabled ? 1 : 0) : input.enabled ? 1 : 0, stringify(input.manifest ?? cur.manifest), now, ownerId, id); return this.getSkill(ownerId, id); }
  deleteSkill(ownerId: string, id: string): void { const skill = this.getSkill(ownerId, id); if (skill.builtIn) throw new Error("Built-in skills cannot be deleted. Disable them instead."); this.db.prepare("DELETE FROM skills WHERE owner_id = ? AND id = ?").run(ownerId, id); }

  listMcpServers(ownerId: string): McpServer[] { return (this.db.prepare("SELECT * FROM mcp_servers WHERE owner_id = ? ORDER BY name").all(ownerId) as Row[]).map(mapMcpServer); }
  enabledMcpServers(ownerId: string, projectId: string | null): McpServer[] { return this.listMcpServers(ownerId).filter((s) => s.enabled && s.tools.length > 0 && (s.projectId === null || s.projectId === projectId)); }
  saveMcpServer(ownerId: string, input: Omit<McpServer, "ownerId" | "createdAt" | "updatedAt">): McpServer { const now = iso(); this.db.prepare(`INSERT INTO mcp_servers (id, owner_id, name, transport, command, args, url, tools, enabled, project_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET name = excluded.name, transport = excluded.transport, command = excluded.command, args = excluded.args, url = excluded.url, tools = excluded.tools, enabled = excluded.enabled, project_id = excluded.project_id, updated_at = excluded.updated_at`).run(input.id, ownerId, input.name, input.transport, input.command, stringify(input.args), input.url, stringify(input.tools), input.enabled ? 1 : 0, input.projectId, now, now); return this.getMcpServer(ownerId, input.id); }
  getMcpServer(ownerId: string, id: string): McpServer { const row = this.db.prepare("SELECT * FROM mcp_servers WHERE owner_id = ? AND id = ?").get(ownerId, id) as Row | undefined; if (!row) throw new Error("MCP server not found."); return mapMcpServer(row); }
  updateMcpServer(ownerId: string, id: string, input: UpdateMcpServerRequest): McpServer { const cur = this.getMcpServer(ownerId, id); return this.saveMcpServer(ownerId, { id: cur.id, name: input.name ?? cur.name, transport: input.transport ?? cur.transport, command: input.command === undefined ? cur.command : input.command, args: input.args ?? cur.args, url: input.url === undefined ? cur.url : input.url, tools: input.tools ?? cur.tools, enabled: input.enabled ?? cur.enabled, projectId: input.projectId === undefined ? cur.projectId : input.projectId }); }
  deleteMcpServer(ownerId: string, id: string): void { this.db.prepare("DELETE FROM mcp_servers WHERE owner_id = ? AND id = ?").run(ownerId, id); }

  listWorkspaces(ownerId: string): Workspace[] { return (this.db.prepare("SELECT * FROM workspaces WHERE owner_id = ? ORDER BY name").all(ownerId) as Row[]).map(mapWorkspace); }
  registerWorkspace(ownerId: string, input: RegisterWorkspaceRequest): Workspace { const now = iso(); const id = randomUUID(); this.db.prepare("INSERT INTO workspaces (id, owner_id, name, root_path, enabled, created_at, updated_at) VALUES (?, ?, ?, ?, 1, ?, ?)").run(id, ownerId, input.name, path.resolve(input.rootPath), now, now); return mapWorkspace(this.db.prepare("SELECT * FROM workspaces WHERE id = ?").get(id) as Row); }
  getWorkspace(ownerId: string, id: string): Workspace { const row = this.db.prepare("SELECT * FROM workspaces WHERE owner_id = ? AND id = ?").get(ownerId, id) as Row | undefined; if (!row) throw new Error("Workspace not found."); const workspace = mapWorkspace(row); if (!workspace.enabled) throw new Error("Workspace is disabled."); return workspace; }
  updateWorkspace(ownerId: string, id: string, input: UpdateWorkspaceRequest): Workspace { const current = mapWorkspace(this.db.prepare("SELECT * FROM workspaces WHERE owner_id = ? AND id = ?").get(ownerId, id) as Row); const now = iso(); this.db.prepare("UPDATE workspaces SET name = ?, enabled = ?, updated_at = ? WHERE owner_id = ? AND id = ?").run(input.name ?? current.name, input.enabled === undefined ? (current.enabled ? 1 : 0) : input.enabled ? 1 : 0, now, ownerId, id); return mapWorkspace(this.db.prepare("SELECT * FROM workspaces WHERE id = ?").get(id) as Row); }
  deleteWorkspace(ownerId: string, id: string): void { this.db.prepare("DELETE FROM workspaces WHERE owner_id = ? AND id = ?").run(ownerId, id); }
  createToolRun(ownerId: string, input: Pick<ToolRun, "chatId" | "workspaceId" | "toolName" | "input">): ToolRun { const now = iso(); const id = randomUUID(); this.db.prepare("INSERT INTO tool_runs (id, owner_id, chat_id, workspace_id, tool_name, status, input, output, error, created_at, updated_at) VALUES (?, ?, ?, ?, ?, 'running', ?, '{}', NULL, ?, ?)").run(id, ownerId, input.chatId, input.workspaceId, input.toolName, stringify(input.input), now, now); return mapToolRun(this.db.prepare("SELECT * FROM tool_runs WHERE id = ?").get(id) as Row); }
  finishToolRun(id: string, status: ToolRun["status"], output: Record<string, unknown>, error: string | null): ToolRun { const now = iso(); this.db.prepare("UPDATE tool_runs SET status = ?, output = ?, error = ?, updated_at = ? WHERE id = ?").run(status, stringify(output), error, now, id); return mapToolRun(this.db.prepare("SELECT * FROM tool_runs WHERE id = ?").get(id) as Row); }
  clearAllData(ownerId: string): void {
    const run = this.db.transaction(() => {
      this.db.prepare("DELETE FROM tool_runs WHERE owner_id = ?").run(ownerId);
      this.db.prepare("DELETE FROM artifacts WHERE owner_id = ?").run(ownerId);
      this.db.prepare("DELETE FROM project_chat_references WHERE owner_id = ?").run(ownerId);
      this.db.prepare("DELETE FROM chats WHERE owner_id = ?").run(ownerId);
      this.db.prepare("DELETE FROM project_references WHERE owner_id = ?").run(ownerId);
      this.db.prepare("DELETE FROM projects WHERE owner_id = ?").run(ownerId);
      this.db.prepare("DELETE FROM mcp_servers WHERE owner_id = ?").run(ownerId);
      this.db.prepare("DELETE FROM workspaces WHERE owner_id = ?").run(ownerId);
      this.db.prepare("DELETE FROM skills WHERE owner_id = ?").run(ownerId);
      for (const skill of builtInSkills) this.upsertSkill(ownerId, skill, true, null);
    });
    run();
  }
  close(): void { this.db.close(); }

  private migrate(): void { this.db.exec(`
    CREATE TABLE IF NOT EXISTS owners (id TEXT PRIMARY KEY, login TEXT NOT NULL, display_name TEXT, avatar_url TEXT, auth_provider TEXT NOT NULL, created_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS auth_tokens (provider TEXT NOT NULL, owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE, access_token TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY (provider, owner_id));
    CREATE TABLE IF NOT EXISTS projects (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE, name TEXT NOT NULL, description TEXT, instructions TEXT, memory TEXT, default_model TEXT, favorite INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS project_references (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE, project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE, title TEXT NOT NULL, content TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS project_chat_references (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE, project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE, source_chat_id TEXT NOT NULL REFERENCES chats(id) ON DELETE CASCADE, source_message_id TEXT NOT NULL REFERENCES messages(id) ON DELETE CASCADE, title TEXT NOT NULL, excerpt TEXT NOT NULL, created_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS workspaces (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE, name TEXT NOT NULL, root_path TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS chats (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE, project_id TEXT REFERENCES projects(id) ON DELETE SET NULL, workspace_id TEXT REFERENCES workspaces(id) ON DELETE SET NULL, title TEXT NOT NULL, title_manually_set INTEGER NOT NULL DEFAULT 0, archived INTEGER NOT NULL DEFAULT 0, favorite INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY, chat_id TEXT NOT NULL REFERENCES chats(id) ON DELETE CASCADE, role TEXT NOT NULL, content TEXT NOT NULL, provider TEXT, metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS message_attachments (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE, chat_id TEXT NOT NULL REFERENCES chats(id) ON DELETE CASCADE, message_id TEXT NOT NULL REFERENCES messages(id) ON DELETE CASCADE, name TEXT NOT NULL, mime_type TEXT NOT NULL, size INTEGER NOT NULL, data TEXT NOT NULL, created_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS artifacts (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE, project_id TEXT REFERENCES projects(id) ON DELETE SET NULL, chat_id TEXT REFERENCES chats(id) ON DELETE SET NULL, message_id TEXT REFERENCES messages(id) ON DELETE SET NULL, title TEXT NOT NULL, kind TEXT NOT NULL, language TEXT, content TEXT NOT NULL, version INTEGER NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS skills (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE, project_id TEXT REFERENCES projects(id) ON DELETE CASCADE, enabled INTEGER NOT NULL DEFAULT 1, built_in INTEGER NOT NULL DEFAULT 0, manifest TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS mcp_servers (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE, name TEXT NOT NULL, transport TEXT NOT NULL, command TEXT, args TEXT NOT NULL DEFAULT '[]', url TEXT, tools TEXT NOT NULL DEFAULT '[]', enabled INTEGER NOT NULL DEFAULT 1, project_id TEXT REFERENCES projects(id) ON DELETE CASCADE, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS tool_runs (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE, chat_id TEXT REFERENCES chats(id) ON DELETE SET NULL, workspace_id TEXT REFERENCES workspaces(id) ON DELETE SET NULL, tool_name TEXT NOT NULL, status TEXT NOT NULL, input TEXT NOT NULL, output TEXT NOT NULL, error TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
  `); this.migrateAuthTokensToOwnerScope(); this.ensureColumn("projects", "memory", "TEXT"); this.ensureColumn("projects", "default_model", "TEXT"); this.ensureColumn("projects", "favorite", "INTEGER NOT NULL DEFAULT 0"); this.ensureColumn("chats", "workspace_id", "TEXT REFERENCES workspaces(id) ON DELETE SET NULL"); this.ensureColumn("chats", "provider_session_id", "TEXT"); this.ensureColumn("chats", "provider_session_workspace_path", "TEXT"); this.ensureColumn("chats", "model", "TEXT"); this.ensureColumn("chats", "reasoning_effort", "TEXT"); this.ensureColumn("chats", "context_tier", "TEXT"); this.ensureColumn("chats", "title_manually_set", "INTEGER NOT NULL DEFAULT 0"); this.ensureColumn("chats", "favorite", "INTEGER NOT NULL DEFAULT 0"); this.ensureColumn("artifacts", "file_path", "TEXT"); this.ensureColumn("mcp_servers", "tools", "TEXT NOT NULL DEFAULT '[]'"); this.migrateLegacyPinsToFavorites(); }
  private clearProjectProviderSessions(ownerId: string, projectId: string, updatedAt: string): void { this.db.prepare("UPDATE chats SET provider_session_id = NULL, provider_session_workspace_path = NULL, updated_at = ? WHERE owner_id = ? AND project_id = ?").run(updatedAt, ownerId, projectId); }
  private ensureColumn(table: string, column: string, definition: string): void { const rows = this.db.prepare(`PRAGMA table_info(${table})`).all() as Row[]; if (!rows.some((row) => row.name === column)) this.db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`); }
  private migrateAuthTokensToOwnerScope(): void {
    const columns = this.db.prepare("PRAGMA table_info(auth_tokens)").all() as Row[];
    const provider = columns.find((column) => column.name === "provider");
    const ownerId = columns.find((column) => column.name === "owner_id");
    if (Number(provider?.pk) !== 1 || Number(ownerId?.pk) === 2) return;
    this.db.transaction(() => {
      this.db.exec(`
        CREATE TABLE auth_tokens_owner_scoped (provider TEXT NOT NULL, owner_id TEXT NOT NULL REFERENCES owners(id) ON DELETE CASCADE, access_token TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY (provider, owner_id));
        INSERT INTO auth_tokens_owner_scoped (provider, owner_id, access_token, created_at, updated_at) SELECT provider, owner_id, access_token, created_at, updated_at FROM auth_tokens;
        DROP TABLE auth_tokens;
        ALTER TABLE auth_tokens_owner_scoped RENAME TO auth_tokens;
      `);
    })();
  }
  private migrateLegacyPinsToFavorites(): void { for (const table of ["projects", "chats"]) { const rows = this.db.prepare(`PRAGMA table_info(${table})`).all() as Row[]; if (rows.some((row) => row.name === "pinned")) this.db.prepare(`UPDATE ${table} SET favorite = 1 WHERE pinned = 1`).run(); } }
  private seed(): void { const existing = this.db.prepare("SELECT id FROM owners LIMIT 1").get() as Row | undefined; const now = iso(); const ownerId = typeof existing?.id === "string" ? existing.id : "local"; if (!existing) this.db.prepare("INSERT INTO owners (id, login, display_name, avatar_url, auth_provider, created_at) VALUES (?, 'local', 'Local user', NULL, 'local', ?)").run(ownerId, now); for (const skill of builtInSkills) this.upsertSkill(ownerId, skill, true, null); }
}
function iso(): string { return new Date().toISOString(); }
function skillRowId(ownerId: string, manifestId: string): string { return ownerId === "local" ? manifestId : `${ownerId}:${manifestId}`; }
function mapOwner(row: Row): Owner { return { id: String(row.id), login: String(row.login), displayName: nullableString(row.display_name), avatarUrl: nullableString(row.avatar_url), authProvider: row.auth_provider === "github" ? "github" : "local" }; }
function mapProject(row: Row): Project { return { id: String(row.id), ownerId: String(row.owner_id), name: String(row.name), description: nullableString(row.description), instructions: nullableString(row.instructions), memory: nullableString(row.memory), defaultModel: nullableString(row.default_model), favorite: Boolean(row.favorite), createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }
function mapProjectReference(row: Row): ProjectReference { return { id: String(row.id), ownerId: String(row.owner_id), projectId: String(row.project_id), title: String(row.title), content: String(row.content), createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }
function mapProjectChatReference(row: Row): ProjectChatReference { return { id: String(row.id), ownerId: String(row.owner_id), projectId: String(row.project_id), sourceChatId: String(row.source_chat_id), sourceMessageId: String(row.source_message_id), title: String(row.title), excerpt: String(row.excerpt), createdAt: String(row.created_at) }; }
function mapChat(row: Row): Chat { return { id: String(row.id), ownerId: String(row.owner_id), projectId: nullableString(row.project_id), workspaceId: nullableString(row.workspace_id), providerSessionId: nullableString(row.provider_session_id), providerSessionWorkspacePath: nullableString(row.provider_session_workspace_path), model: nullableString(row.model), reasoningEffort: normalizeReasoningEffort(row.reasoning_effort), contextTier: normalizeContextTier(row.context_tier), title: String(row.title), titleManuallySet: Boolean(row.title_manually_set), archived: Boolean(row.archived), favorite: Boolean(row.favorite), createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }
function mapMessage(row: Row): ChatMessage { return { id: String(row.id), chatId: String(row.chat_id), role: normalizeRole(row.role), content: String(row.content), provider: nullableString(row.provider), metadata: parseObject(row.metadata), createdAt: String(row.created_at) }; }
function mapMessageAttachment(row: Row): MessageAttachment { const attachment: MessageAttachment = { id: String(row.id), name: String(row.name), mimeType: String(row.mime_type), size: Number(row.size) }; if (typeof row.data === "string" && row.data) attachment.data = row.data; return attachment; }
function mapArtifact(row: Row): Artifact { return { id: String(row.id), ownerId: String(row.owner_id), projectId: nullableString(row.project_id), chatId: nullableString(row.chat_id), messageId: nullableString(row.message_id), filePath: nullableString(row.file_path), title: String(row.title), kind: normalizeArtifactKind(row.kind), language: nullableString(row.language), content: String(row.content), version: Number(row.version), createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }
function mapArtifactSummary(row: Row): ArtifactSummary { return { id: String(row.id), ownerId: String(row.owner_id), projectId: nullableString(row.project_id), chatId: nullableString(row.chat_id), messageId: nullableString(row.message_id), filePath: nullableString(row.file_path), title: String(row.title), kind: normalizeArtifactKind(row.kind), language: nullableString(row.language), contentPreview: typeof row.content_preview === "string" ? row.content_preview : "", contentLength: Number(row.content_length ?? 0), version: Number(row.version), createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }
function mapSkill(row: Row): Skill { return { id: String(row.id), ownerId: String(row.owner_id), projectId: nullableString(row.project_id), enabled: Boolean(row.enabled), builtIn: Boolean(row.built_in), manifest: parseObject(row.manifest) as SkillManifest, createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }
function mapMcpServer(row: Row): McpServer { return { id: String(row.id), ownerId: String(row.owner_id), name: String(row.name), transport: row.transport === "http" ? "http" : row.transport === "sse" ? "sse" : "stdio", command: nullableString(row.command), args: parseArray(row.args).map(String), url: nullableString(row.url), tools: parseArray(row.tools).map(String), enabled: Boolean(row.enabled), projectId: nullableString(row.project_id), createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }
function mapWorkspace(row: Row): Workspace { return { id: String(row.id), ownerId: String(row.owner_id), name: String(row.name), rootPath: String(row.root_path), enabled: Boolean(row.enabled), createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }
function mapToolRun(row: Row): ToolRun { return { id: String(row.id), ownerId: String(row.owner_id), chatId: nullableString(row.chat_id), workspaceId: nullableString(row.workspace_id), toolName: String(row.tool_name), status: normalizeToolRunStatus(row.status), input: parseObject(row.input), output: parseObject(row.output), error: nullableString(row.error), createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }
function stringify(v: unknown): string { return JSON.stringify(v); }
function withoutRuntimeAttachments(metadata: Record<string, unknown>): Record<string, unknown> { const rest = { ...metadata }; delete rest.attachments; return rest; }
function parseObject(v: unknown): Record<string, unknown> { if (typeof v !== "string") return {}; const parsed = JSON.parse(v) as unknown; return typeof parsed === "object" && parsed !== null && !Array.isArray(parsed) ? parsed as Record<string, unknown> : {}; }
function parseArray(v: unknown): unknown[] { if (typeof v !== "string") return []; const parsed = JSON.parse(v) as unknown; return Array.isArray(parsed) ? parsed : []; }
function nullableString(v: unknown): string | null { return typeof v === "string" && v.length > 0 ? v : null; }
function excerptText(value: string): string { const compact = value.replace(/\s+/g, " ").trim(); return compact.length > 420 ? `${compact.slice(0, 417)}...` : compact; }
function clampContent(value: string, max: number): string { const compact = value.replace(/\s+/g, " ").trim(); return compact.length > max ? `${compact.slice(0, Math.max(0, max - 3))}...` : compact; }
function clampLimit(value: number | undefined, fallback: number, max: number): number { if (typeof value !== "number" || !Number.isFinite(value)) return fallback; return Math.min(Math.max(1, Math.trunc(value)), max); }
function conversationScopeClause(scope: ConversationScope, currentProjectId: string | null, excludeChatId: string | null): { clause: string; params: string[] } {
  const params: string[] = [];
  let clause = "";
  if (scope === "current_project") {
    if (currentProjectId) { clause += " AND chats.project_id = ?"; params.push(currentProjectId); }
    else clause += " AND chats.project_id IS NULL";
  } else if (scope === "other_projects") {
    if (currentProjectId) { clause += " AND (chats.project_id IS NULL OR chats.project_id != ?)"; params.push(currentProjectId); }
    else clause += " AND chats.project_id IS NOT NULL";
  }
  if (excludeChatId) { clause += " AND chats.id != ?"; params.push(excludeChatId); }
  return { clause, params };
}
function normalizeRole(v: unknown): ChatMessage["role"] { return v === "assistant" || v === "system" || v === "tool" ? v : "user"; }
function normalizeReasoningEffort(v: unknown): Chat["reasoningEffort"] { const effort = nullableString(v); return effort === "default" || effort === "none" || effort === "low" || effort === "medium" || effort === "high" || effort === "xhigh" || effort === "max" ? effort : null; }
function normalizeContextTier(v: unknown): Chat["contextTier"] { const tier = nullableString(v); return tier === "default" || tier === "long_context" ? tier : null; }
function normalizeArtifactKind(v: unknown): Artifact["kind"] { const kind = String(v); return kind === "markdown" || kind === "code" || kind === "json" || kind === "mermaid" || kind === "html" || kind === "file-bundle" ? kind : "text"; }
function normalizeToolRunStatus(v: unknown): ToolRun["status"] { const status = String(v); return status === "queued" || status === "running" || status === "succeeded" || status === "failed" || status === "cancelled" ? status : "failed"; }
function shouldActivateSkill(skill: Skill, explicitIds: Set<string>, content: string): boolean {
  if (explicitIds.has(skill.id)) return true;
  const text = normalizeActivationText(content);
  if (!text) return false;
  if (matchesActivationText(text, skill.id) || matchesActivationText(text, skill.manifest.name)) return true;
  return skill.manifest.activationRules.some((rule) => matchesActivationRule(text, rule));
}
function matchesActivationRule(text: string, rule: string): boolean {
  const ruleText = normalizeActivationText(rule).replace(/\buser\b|\basks?\b|\bfor\b|\ba\b|\ban\b|\bthe\b|\bshares?\b|\brequests?\b|\bwhen\b|\babout\b/g, " ").replace(/\s+/g, " ").trim();
  if (!ruleText) return false;
  if (matchesActivationText(text, ruleText)) return true;
  return ruleText.split(" ").filter((word) => word.length >= 4).some((word) => text.includes(word));
}
function matchesActivationText(text: string, value: string): boolean {
  const normalized = normalizeActivationText(value);
  if (!normalized) return false;
  return text.includes(normalized) || text.includes(normalized.replace(/\s+/g, "-"));
}
function normalizeActivationText(value: string): string { return value.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim(); }
